apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-httpd
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: sneakybytes/capstone-httpd
        name: webapp
        ports:
        - containerPort: 80
